// <auto-generated />
using System;
using ChineseAuctionAPI.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ChineseAuctionAPI.Migrations
{
    [DbContext(typeof(SaleContextDB))]
    [Migration("20251221191350_InitialCreate5")]
    partial class InitialCreate5
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ChineseAuctionAPI.Models.Card", b =>
                {
                    b.Property<int>("IdCard")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdCard"));

                    b.Property<int>("IdBuyer")
                        .HasColumnType("int");

                    b.Property<int>("IdGift")
                        .HasColumnType("int");

                    b.Property<int?>("PackageIdPackage")
                        .HasColumnType("int");

                    b.Property<int>("Price")
                        .HasColumnType("int");

                    b.Property<int?>("UserIdUser")
                        .HasColumnType("int");

                    b.HasKey("IdCard");

                    b.HasIndex("PackageIdPackage");

                    b.HasIndex("UserIdUser");

                    b.ToTable("cards");
                });

            modelBuilder.Entity("ChineseAuctionAPI.Models.Donor", b =>
                {
                    b.Property<int>("IdDonor")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdDonor"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdDonor");

                    b.ToTable("Donors");
                });

            modelBuilder.Entity("ChineseAuctionAPI.Models.Gift", b =>
                {
                    b.Property<int>("IdGift")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdGift"));

                    b.Property<int>("Amount")
                        .HasColumnType("int");

                    b.Property<int>("Category")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("DonorIdDonor")
                        .HasColumnType("int");

                    b.Property<int>("IdDonor")
                        .HasColumnType("int");

                    b.Property<string>("Image")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDrawn")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdGift");

                    b.HasIndex("DonorIdDonor");

                    b.ToTable("Gifts");
                });

            modelBuilder.Entity("ChineseAuctionAPI.Models.Order", b =>
                {
                    b.Property<int>("IdOrder")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdOrder"));

                    b.Property<int>("Amount")
                        .HasColumnType("int");

                    b.Property<int>("IdUser")
                        .HasColumnType("int");

                    b.Property<bool>("IsStatusDraft")
                        .HasColumnType("bit");

                    b.Property<DateTime>("OrderDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("UserIdUser")
                        .HasColumnType("int");

                    b.HasKey("IdOrder");

                    b.HasIndex("UserIdUser");

                    b.ToTable("OrdersOrders");
                });

            modelBuilder.Entity("ChineseAuctionAPI.Models.OrdersGift", b =>
                {
                    b.Property<int>("IdOrdersGift")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdOrdersGift"));

                    b.Property<int>("Amount")
                        .HasColumnType("int");

                    b.Property<int>("GiftIdGift")
                        .HasColumnType("int");

                    b.Property<int>("IdGift")
                        .HasColumnType("int");

                    b.Property<int>("IdOrder")
                        .HasColumnType("int");

                    b.Property<int>("OrderIdOrder")
                        .HasColumnType("int");

                    b.HasKey("IdOrdersGift");

                    b.HasIndex("GiftIdGift");

                    b.HasIndex("OrderIdOrder");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("ChineseAuctionAPI.Models.Package", b =>
                {
                    b.Property<int>("IdPackage")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdPackage"));

                    b.Property<int?>("AmountPremium")
                        .HasColumnType("int");

                    b.Property<int>("AmountRegular")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("OrderIdOrder")
                        .HasColumnType("int");

                    b.Property<int>("Price")
                        .HasColumnType("int");

                    b.HasKey("IdPackage");

                    b.HasIndex("OrderIdOrder");

                    b.ToTable("Packages");
                });

            modelBuilder.Entity("ChineseAuctionAPI.Models.User", b =>
                {
                    b.Property<int>("IdUser")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdUser"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Identity")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("IsManager")
                        .HasColumnType("int");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdUser");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasFilter("[Email] IS NOT NULL");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("ChineseAuctionAPI.Models.Winner", b =>
                {
                    b.Property<int>("IdWinner")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdWinner"));

                    b.Property<int>("IdGift")
                        .HasColumnType("int");

                    b.Property<int>("IdUser")
                        .HasColumnType("int");

                    b.HasKey("IdWinner");

                    b.ToTable("winners");
                });

            modelBuilder.Entity("ChineseAuctionAPI.Models.Card", b =>
                {
                    b.HasOne("ChineseAuctionAPI.Models.Package", null)
                        .WithMany("Cards")
                        .HasForeignKey("PackageIdPackage");

                    b.HasOne("ChineseAuctionAPI.Models.User", null)
                        .WithMany("Cards")
                        .HasForeignKey("UserIdUser");
                });

            modelBuilder.Entity("ChineseAuctionAPI.Models.Gift", b =>
                {
                    b.HasOne("ChineseAuctionAPI.Models.Donor", "Donor")
                        .WithMany()
                        .HasForeignKey("DonorIdDonor")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Donor");
                });

            modelBuilder.Entity("ChineseAuctionAPI.Models.Order", b =>
                {
                    b.HasOne("ChineseAuctionAPI.Models.User", "User")
                        .WithMany("Orders")
                        .HasForeignKey("UserIdUser")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("ChineseAuctionAPI.Models.OrdersGift", b =>
                {
                    b.HasOne("ChineseAuctionAPI.Models.Gift", "Gift")
                        .WithMany("OrdersGifts")
                        .HasForeignKey("GiftIdGift")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ChineseAuctionAPI.Models.Order", "Order")
                        .WithMany("Orders")
                        .HasForeignKey("OrderIdOrder")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Gift");

                    b.Navigation("Order");
                });

            modelBuilder.Entity("ChineseAuctionAPI.Models.Package", b =>
                {
                    b.HasOne("ChineseAuctionAPI.Models.Order", null)
                        .WithMany("Package")
                        .HasForeignKey("OrderIdOrder");
                });

            modelBuilder.Entity("ChineseAuctionAPI.Models.Gift", b =>
                {
                    b.Navigation("OrdersGifts");
                });

            modelBuilder.Entity("ChineseAuctionAPI.Models.Order", b =>
                {
                    b.Navigation("Orders");

                    b.Navigation("Package");
                });

            modelBuilder.Entity("ChineseAuctionAPI.Models.Package", b =>
                {
                    b.Navigation("Cards");
                });

            modelBuilder.Entity("ChineseAuctionAPI.Models.User", b =>
                {
                    b.Navigation("Cards");

                    b.Navigation("Orders");
                });
#pragma warning restore 612, 618
        }
    }
}
